version: "3.8"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "123456" # 配置root用户密码
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MYSQL_PASSWORD: "123123" # 业务库密码

  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/

  gpt-share-server:
    image: jurieo/gpt-share-server:undefined #商业版标签是undefined，免费版是latest
    restart: always
    ports:
      - 38300:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
      # 内容审核及速率限制
      AUDIT_LIMIT_URL: "http://auditlimit:8080/audit_limit"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data/chatgpt-share-server/:/app/data/
      - ./data/images:/app/resource/public/images/

    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-share-server"

  # 使用我二开的auditlimit可以按单个用户限制使用次数。
  auditlimit:
    image: jurieo/auditlimit
    restart: always
    # ports:
    #   - 9611:8080
    environment:
      LIMIT: 40 # 限制每个userToken允许的次数
      PER: "3h" # 限制周期 1s, 1m, 1h, 1d, 1w, 1y
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-share-server"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope xyhelper-chatgpt-share-server --cleanup
    restart: always
    environment:
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-share-server"

  # mysql定时备份,有需要可以开启，建议单独开个compose，不然每次重启都会花30s左右的时间
  # mysql-backup:
  #   image: databack/mysql-backup
  #   restart: always
  #   user: root
  #   volumes:
  #     - ./mysql-backup:/db # 备份文件存放目录
  #   environment:
  #     TZ: Asia/Shanghai
  #     DB_SERVER: "mysql"
  #     DB_PORT: "3306"
  #     DB_USER: "root"
  #     DB_PASS: "123456" # root密码
  #     DB_HOST: "mysql"
  #     DB_NAMES: "cool" # 备份数据库名，多个库名用,分隔
  #     DB_DUMP_FREQ: "60" # 每60分钟一次
  #     DB_DUMP_BEGIN: "+1" # 什么时间进行第一次转储，这里是启动后一分钟开始第一次备份
  #     DB_DUMP_DEBUG: "false"
  #     DB_DUMP_TARGET: "/db"
  #   depends_on:
  #     - mysql
